# Generated by Django 5.0.6 on 2024-05-26 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chaiverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('chai_type', models.CharField(choices=[('PC', 'PLANE CHAI'), ('RC', 'RED CHAI'), ('MC', 'MASALA CHAI'), ('ZC', 'ZINGER CHAI'), ('LC', 'LEMON CHAI ')], max_length=2)),
            ],
        ),
    ]
