# Generated by Django 5.0.6 on 2024-05-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaiverity_description_chaiverity_pirce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaiverity',
            name='pirce',
            field=models.IntegerField(choices=[('20', '20'), ('50', '50'), ('60', '60'), ('100', '100'), ('160', '160')], default=''),
        ),
    ]
