# Generated by Django 5.0.6 on 2024-05-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_alter_chaiverity_pirce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaiverity',
            name='pirce',
            field=models.IntegerField(choices=[('PC', 20), ('RC', 50), ('MC', 60), ('ZC', 100), ('LC', 160)], default=0),
        ),
    ]
