# Generated by Django 5.0.6 on 2024-05-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0007_alter_chaiverity_pirce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaiverity',
            old_name='pirce',
            new_name='price',
        ),
    ]
